/**
 * Manual FAQ Articles Seeder via API
 *
 * This script directly creates FAQ articles via HTTP API calls
 * Run with: yarn medusa exec ./src/scripts/manual-seed-faq.ts
 */

const FAQ_ARTICLES = [
  // ── Buying & Orders ──────────────────────────────────
  { title: "How do I track my order?", description: "Find out the current status and location of your order.", section: "buying", content: "Track your orders from the My Orders page in your account. You'll see real-time updates on order status.", display_order: 1 },
  { title: "How do I cancel an order?", description: "Learn about the cancellation window and how to request a cancellation.", section: "buying", content: "Orders can be cancelled within 12 hours of placement. Go to My Orders and select the order to cancel.", display_order: 2 },
  { title: "Can I modify my order?", description: "Information about order modifications and deadlines.", section: "buying", content: "Order modifications are only possible within 1 hour of placement. Contact support for urgent changes.", display_order: 3 },
  { title: "How do I return an item?", description: "Learn about our return process and policy.", section: "buying", content: "We offer hassle-free returns within 14 days of delivery. Submit a return request in My Orders.", display_order: 4 },
  { title: "What if my item doesn't match the description?", description: "Steps to take if you received a different item than ordered.", section: "buying", content: "If the item doesn't match, contact our support team immediately with photos for verification.", display_order: 5 },
  { title: "How do I apply a coupon or promo code?", description: "Guide to using discount codes and promotional offers.", section: "buying", content: "Enter the promo code at checkout in the 'Apply Coupon' field. Discount will be applied automatically.", display_order: 6 },
  { title: "Are there any hidden charges?", description: "Information about all fees included in your order total.", section: "buying", content: "No hidden charges. All fees (shipping, taxes, convenience fees) are displayed before checkout.", display_order: 7 },
  { title: "Can I place an order for someone else?", description: "Guide to gifting and ordering for others.", section: "buying", content: "Yes, you can provide a different delivery address during checkout. The recipient will not see your billing info.", display_order: 8 },
  { title: "What is the bulk order policy?", description: "Information about ordering large quantities.", section: "buying", content: "For bulk orders above 50 items, please contact our sales team for special pricing and arrangements.", display_order: 9 },
  { title: "How do I get an invoice for my order?", description: "Steps to download and view your order invoice.", section: "buying", content: "Go to My Orders, select the order, and click 'Download Invoice'. It will be in PDF format.", display_order: 10 },
  { title: "Can I change my order after placing it?", description: "Information about editing orders post-placement.", section: "buying", content: "Changes are only possible within 1 hour. After that, you'll need to cancel and place a new order.", display_order: 11 },
  { title: "What happens if I don't receive my order?", description: "Steps to take if your order doesn't arrive.", section: "buying", content: "Wait 1-2 days after delivery date. If not received, contact support with order tracking screenshot.", display_order: 12 },
  { title: "Is there a warranty on products?", description: "Information about product warranties and guarantees.", section: "buying", content: "Warranty varies by product. Check product details page for manufacturer warranty information.", display_order: 13 },
  { title: "What is your return and refund policy?", description: "Complete refund and return policy details.", section: "buying", content: "30 days full refund on most items. Non-returnable items clearly marked at purchase. Refunds to original payment method.", display_order: 14 },
  { title: "How do I know when my refund has been processed?", description: "Steps to track refund status after initiating return.", section: "buying", content: "You'll receive an email notification when refund is initiated. Bank processing takes 5-7 business days.", display_order: 15 },
  { title: "Can I exchange an item instead of returning it?", description: "Information about product exchange process.", section: "buying", content: "Yes, exchange is available within 7 days. Choose a replacement of equal or higher value without additional fees.", display_order: 16 },
  { title: "What are the conditions for returning products?", description: "Requirements for items eligible for return.", section: "buying", content: "Items must be unused, original packaging intact, with all accessories. Items damaged by misuse cannot be returned.", display_order: 17 },

  // ── Shipping ──────────────────────────────────────────
  { title: "How long does delivery take?", description: "Information about standard and express delivery timelines.", section: "shipping", content: "Standard delivery takes 3-7 business days. Express delivery available in select metro cities.", display_order: 1 },
  { title: "What are shipping costs?", description: "Learn about shipping charges and free shipping eligibility.", section: "shipping", content: "Shipping costs vary by location and weight. Free shipping available on orders above ₹500.", display_order: 2 },
  { title: "Can I change my delivery address after ordering?", description: "Instructions for updating your shipping address.", section: "shipping", content: "Address changes must be made within 2 hours of order placement. Contact support immediately.", display_order: 3 },
  { title: "What if my order is lost or damaged?", description: "Steps to take if your package arrives damaged or doesn't arrive.", section: "shipping", content: "Contact support within 7 days with proof of damage or non-delivery. We'll arrange replacement/refund.", display_order: 4 },
  { title: "Which areas do you deliver to?", description: "Information about our delivery coverage and serviceable areas.", section: "shipping", content: "We deliver across India including metros, tier-2 cities, and select rural areas. Enter your pincode to check.", display_order: 5 },
  { title: "Can I track my shipment in real-time?", description: "Guide to tracking shipment location and delivery status.", section: "shipping", content: "Yes, tracking information updates in real-time. Check My Orders page for live location updates.", display_order: 6 },
  { title: "Do you offer same-day or next-day delivery?", description: "Information about express delivery options.", section: "shipping", content: "Same-day delivery available in select metro areas for orders before 11 AM. Next-day delivery available widely.", display_order: 7 },
  { title: "What if my address is incomplete or incorrect?", description: "Steps to correct address before delivery.", section: "shipping", content: "Correct the address immediately after placing the order. Call us for urgent corrections after shipment.", display_order: 8 },
  { title: "Can I have my order delivered to my office?", description: "Options for workplace delivery.", section: "shipping", content: "Yes, you can provide your office address as delivery location during checkout.", display_order: 9 },
  { title: "What if I'm not home when the delivery arrives?", description: "Options for failed delivery attempts.", section: "shipping", content: "Our delivery partner will attempt delivery 3 times. You can reschedule or arrange another time.", display_order: 10 },
  { title: "Do you deliver on holidays?", description: "Information about holiday delivery schedules.", section: "shipping", content: "Limited delivery on national holidays. Check estimated delivery date at checkout for holiday schedules.", display_order: 11 },
  { title: "What should I do if delivery is delayed?", description: "Steps to take if order takes longer than expected.", section: "shipping", content: "Contact support if delivery exceeds estimated date. We'll investigate with carrier and provide compensation if applicable.", display_order: 12 },
  { title: "Can I schedule a delivery for a specific time?", description: "Options for time slot selection and delivery scheduling.", section: "shipping", content: "Yes, select preferred time slot during checkout. Delivery partners will attempt delivery within that window.", display_order: 13 },

  // ── Payments ──────────────────────────────────────────
  { title: "What payment methods do you accept?", description: "Information about all available payment options.", section: "payments", content: "We accept credit/debit cards, UPI, net banking, digital wallets, and cash on delivery (COD).", display_order: 1 },
  { title: "Why does Himanshu use Razorpay?", description: "Information about our payment provider and security.", section: "payments", content: "Razorpay is PCI-DSS Level 1 certified and trusted by 500,000+ businesses. It's India's most secure payment gateway.", display_order: 2 },
  { title: "Does Himanshu store my credit card details?", description: "Clarification about card data storage and security.", section: "payments", content: "No, we never store your full credit card details. Only the last 4 digits are saved for reference.", display_order: 3 },
  { title: "Is UPI payment safe? What information do you access?", description: "Security details about UPI transactions.", section: "payments", content: "UPI is NPCI regulated and extremely safe. We only receive transaction ID, amount, and timestamp.", display_order: 4 },
  { title: "How secure is net banking on Himanshu?", description: "Security measures for net banking transactions.", section: "payments", content: "We use 256-bit SSL encryption and 2FA for maximum security. Your bank details are never stored.", display_order: 5 },
  { title: "Can I save my card for future purchases?", description: "Information about card tokenization and saved payments.", section: "payments", content: "Yes, card tokenization is secure and PCI-DSS compliant. Your card is encrypted and safe.", display_order: 6 },
  { title: "What if my payment failed but amount was deducted?", description: "Process for handling failed payment transactions.", section: "payments", content: "Refunds are automatic within 5-7 business days. No action needed. Your bank will credit the amount.", display_order: 7 },
  { title: "Is cash on delivery available everywhere?", description: "Information about COD service areas and eligibility.", section: "payments", content: "COD available in most areas except select pincode zones. Check availability at checkout.", display_order: 8 },
  { title: "Can I change payment method after checkout?", description: "Options to modify payment information.", section: "payments", content: "Payment method can be changed before payment confirmation. After that, you'll need to place a new order.", display_order: 9 },
  { title: "Do you charge any convenience fee?", description: "Information about additional charges on payments.", section: "payments", content: "A small convenience fee applies to some payment methods. This is clearly displayed before you confirm payment.", display_order: 10 },
  { title: "How are refunds processed?", description: "Complete guide to refund process and timelines.", section: "payments", content: "Refunds are processed within 5-7 business days to the original payment method. COD refunds via bank transfer.", display_order: 11 },
  { title: "Can I use multiple payment methods for one order?", description: "Information about split payments.", section: "payments", content: "Currently, only one payment method per order is allowed. You can combine wallet balance with another method.", display_order: 12 },
  { title: "What encryption protocol do you use?", description: "Technical details about payment security.", section: "payments", content: "We use TLS 1.2+ encryption for all transactions. Razorpay uses end-to-end encryption for card data.", display_order: 13 },
  { title: "Do you store OTP or security codes?", description: "Clarification about sensitive payment data storage.", section: "payments", content: "No, OTPs and security codes are never stored. They are used only for transaction verification and discarded.", display_order: 14 },
  { title: "Can I see my payment history?", description: "Guide to viewing past transactions and payments.", section: "payments", content: "Yes, all payment history is available in My Account > Payment History with transaction details.", display_order: 15 },
  { title: "Are my payment details secure during checkout?", description: "Security measures during payment process.", section: "payments", content: "Checkout page uses 256-bit SSL encryption. Look for padlock icon in URL bar. Never enter sensitive info on non-HTTPS pages.", display_order: 16 },
  { title: "What is PCI-DSS compliance?", description: "Explanation of PCI-DSS security standard.", section: "payments", content: "PCI-DSS is the payment card industry security standard. Razorpay's Level 1 certification is the highest security level available.", display_order: 17 },
  { title: "Can I get a refund for digital products?", description: "Information about refunds for downloads and digital items.", section: "payments", content: "Digital items are non-refundable once delivered. Physical items follow standard 14-day return policy.", display_order: 18 },
  { title: "How do I use gift cards on Himanshu?", description: "Steps to purchase and redeem gift cards.", section: "payments", content: "Buy gift cards from My Account > Gift Cards section. Recipients can redeem during checkout. No expiry.", display_order: 19 },
  { title: "Can I purchase gift cards for others?", description: "Information about gifting with Himanshu gift cards.", section: "payments", content: "Yes, purchase e-gift cards and send directly via email with custom message. Recipient gets code to redeem.", display_order: 20 },

  // ── Account ───────────────────────────────────────────
  { title: "How do I reset my password?", description: "Steps to recover and reset your account password.", section: "account", content: "Click 'Forgot Password' on the login page and follow the email instructions within 24 hours.", display_order: 1 },
  { title: "How do I update my profile information?", description: "Guide to changing account details and personal information.", section: "account", content: "Go to My Account > Profile to update your name, phone, email, and other personal details.", display_order: 2 },
  { title: "How do I add or change my address?", description: "Instructions for managing shipping and billing addresses.", section: "account", content: "Go to My Account > Addresses to add, edit, or delete addresses. You can have multiple addresses saved.", display_order: 3 },
  { title: "How do I add items to my wishlist?", description: "Step-by-step guide to save your favorite products for later.", section: "account", content: "Click the heart icon on any product to add it to your wishlist. Access wishlist from My Account anytime.", display_order: 4 },
  { title: "How do I remove items from my wishlist?", description: "Learn how to delete items or clear your entire wishlist.", section: "account", content: "Click the heart icon again to remove items from your wishlist. Or manage from Wishlist page.", display_order: 5 },
  { title: "How do I contact customer support when I get stuck?", description: "Multiple ways to reach our support team for help and issue resolution.", section: "account", content: "Visit My Account > Support to submit tickets or contact us via email/WhatsApp. We respond within 24 hours.", display_order: 6 },
  { title: "What should I do if I get stuck during checkout or order process?", description: "Troubleshooting guide for common checkout and ordering issues.", section: "account", content: "Clear browser cache, try a different browser, check internet connection, or disable ad blockers.", display_order: 7 },
  { title: "Complete guide: Tracking your order from purchase to delivery", description: "Everything you need to know about tracking your order step by step.", section: "account", content: "Your order goes through: confirmed → packed → shipped → in transit → delivered. Check status anytime.", display_order: 8 },
  { title: "How do I delete my account?", description: "Process to close or deactivate your account.", section: "account", content: "Go to My Account > Settings > Close Account. Your data will be deleted after 30 days per privacy policy.", display_order: 9 },
  { title: "Can I have multiple accounts?", description: "Information about account multiplicity and rules.", section: "account", content: "One account per person is recommended. Using multiple accounts may violate our terms of service.", display_order: 10 },
  { title: "How do I update my phone number?", description: "Guide to changing registered phone number.", section: "account", content: "Go to My Account > Profile and update phone number. Verification OTP will be sent to the new number.", display_order: 11 },
  { title: "How do I check my order history?", description: "Guide to viewing all your past orders.", section: "account", content: "Visit My Account > My Orders to see all past orders. Filter by status: pending, delivered, returned, cancelled.", display_order: 12 },
  { title: "Can I view my download/digital items?", description: "Information about accessing digital purchases.", section: "account", content: "Yes, digital items are listed in My Account > Downloads. You can download them anytime after purchase.", display_order: 13 },
  { title: "How do I refer a friend?", description: "Guide to our referral program and rewards.", section: "account", content: "Share your unique referral code from My Account > Referrals. Earn rewards when friends sign up.", display_order: 14 },
  { title: "Can I change my email address?", description: "Process to update your registered email.", section: "account", content: "Go to My Account > Settings > Email Address. Verification link will be sent to your current email.", display_order: 15 },
  { title: "How do I manage my notification preferences?", description: "Guide to customizing notifications and alerts.", section: "account", content: "Go to My Account > Notifications to enable/disable SMS, email, and push notifications.", display_order: 16 },
  { title: "How do I enable two-factor authentication?", description: "Guide to setting up 2FA for account security.", section: "account", content: "Go to My Account > Security > Two-Factor Authentication. Choose SMS or app-based authentication.", display_order: 17 },
  { title: "What should I do if I suspect my account is compromised?", description: "Steps to take if account security is breached.", section: "account", content: "Change password immediately, enable 2FA, review recent orders, and contact support for account review.", display_order: 18 },
  { title: "How do I view my transaction history?", description: "Guide to accessing complete transaction records.", section: "account", content: "Visit My Account > Transaction History. Export options available for tax/accounting purposes.", display_order: 19 },
  { title: "Can I close my account temporarily?", description: "Information about account deactivation vs deletion.", section: "account", content: "Yes, go to Settings > Deactivate Account. Reactivate anytime. Data is preserved for 6 months.", display_order: 20 },

  // ── Trust & Safety ────────────────────────────────────
  { title: "How is my personal data protected?", description: "Information about data protection and privacy measures.", section: "trust", content: "We follow GDPR, CCPA, and Indian data protection laws. All data is encrypted both in transit and at rest.", display_order: 1 },
  { title: "What measures does Himanshu take to prevent fraud?", description: "Security practices and fraud prevention mechanisms.", section: "trust", content: "We use Razorpay (PCI-DSS), monitor transaction patterns, verify addresses, and use AI-based fraud detection.", display_order: 2 },
  { title: "How can I ensure the product I'm buying is authentic?", description: "Tips for verifying product authenticity and identifying counterfeits.", section: "trust", content: "Look for high-rated sellers, reviews with photos, and detailed product specifications. Report suspicious items.", display_order: 3 },
  { title: "How does Himanshu ensure seller credibility?", description: "Information about seller verification and vetting process.", section: "trust", content: "All sellers are verified, rated by customers, and monitored for compliance. We remove fraudulent sellers.", display_order: 4 },
  { title: "What is your privacy policy?", description: "Overview of how your data is collected and used.", section: "trust", content: "Our privacy policy details data collection, usage, and rights. Available at our website footer.", display_order: 5 },
  { title: "Can I report a suspicious or fraudulent listing?", description: "Steps to report fake or misleading listings.", section: "trust", content: "Click 'Report' on any product page and select the issue. Our team reviews and takes action within 24 hours.", display_order: 6 },
  { title: "How is my location data used?", description: "Information about location tracking and usage.", section: "trust", content: "We only use location data for delivery optimization. You can disable location sharing in app settings.", display_order: 7 },
  { title: "Do you comply with data residency requirements?", description: "Information about data storage and localization.", section: "trust", content: "Yes, we comply with all Indian data residency requirements. Customer data is stored on Indian servers.", display_order: 8 },
  { title: "What happens if I dispute a transaction?", description: "Process for disputing fraudulent or incorrect charges.", section: "trust", content: "Contact our support team immediately with details. We'll investigate and work with your bank to resolve.", display_order: 9 },
  { title: "How often is my data backed up?", description: "Information about data backup frequency and disaster recovery.", section: "trust", content: "Your data is backed up daily with redundancy across multiple secure locations for protection.", display_order: 10 },
  { title: "Does Himanshu have any sustainability or eco-friendly initiatives?", description: "Information about environmental practices.", section: "trust", content: "Yes, we use eco-friendly packaging, partner with sustainable sellers, and offset carbon. Learn more on our Sustainability page.", display_order: 11 },
  { title: "Where is Himanshu based and can I visit your office?", description: "Information about company location and office visits.", section: "trust", content: "Himanshu is headquartered in India. Physical office visits by appointment only. Contact support for details.", display_order: 12 },

  // ── Miscellaneous ─────────────────────────────────────
  { title: "How do I search for products on Himanshu?", description: "Guide to using the search functionality to find products.", section: "miscellaneous", content: "Use the search bar at the top of the page. Type product name, brand, or category. Results appear in real-time with suggestions.", display_order: 1 },
  { title: "How do I filter search results?", description: "Learn to narrow down products by filters and specifications.", section: "miscellaneous", content: "Use filters on the left: Price, Rating, Brand, Availability. Mix multiple filters to find exactly what you need.", display_order: 2 },
  { title: "Can I sort products by different criteria?", description: "Information about product sorting options.", section: "miscellaneous", content: "Yes, sort by: Relevance, Price (Low to High), Price (High to Low), Newest, Most Popular, Best Rated.", display_order: 3 },
  { title: "How do I read and understand product reviews?", description: "Guide to evaluating product reviews and ratings.", section: "miscellaneous", content: "Reviews show verified buyer feedback with ratings. Look for detailed reviews with photos for genuine insights.", display_order: 4 },
  { title: "Can I write a review for a product I purchased?", description: "Steps to submit your own product review.", section: "miscellaneous", content: "After delivery, go to My Orders > Product > Write Review. Add rating, title, description, and up to 5 photos.", display_order: 5 },
  { title: "What is the Himanshu loyalty program?", description: "Information about rewards and benefits for regular customers.", section: "miscellaneous", content: "Earn reward points on every purchase. Redeem points for discounts, free shipping, or exclusive offers.", display_order: 6 },
  { title: "How do I earn reward points?", description: "Ways to accumulate points in the loyalty program.", section: "miscellaneous", content: "Earn 1 point per ₹1 spent. Bonus points for referrals, reviews, and birthday purchases. No expiry date.", display_order: 7 },
  { title: "What can I do with my reward points?", description: "Redemption options for accumulated points.", section: "miscellaneous", content: "Redeem 100 points = ₹10 discount. Or use points for free shipping, exclusive products, or special access sales.", display_order: 8 },
  { title: "How do I subscribe to the Himanshu newsletter?", description: "Steps to sign up for email updates and special offers.", section: "miscellaneous", content: "Enter your email at website footer or in Settings > Preferences. Get early access to sales and exclusive deals.", display_order: 9 },
  { title: "Can I customize my email preferences?", description: "Guide to managing notification and email subscriptions.", section: "miscellaneous", content: "Go to My Account > Email Preferences to choose what emails to receive: promotions, updates, newsletters, etc.", display_order: 10 },
  { title: "Does Himanshu have a mobile app?", description: "Information about shopping on mobile and availability of apps.", section: "miscellaneous", content: "Yes, download from App Store (iOS) or Google Play (Android). App features exclusive mobile-only deals.", display_order: 11 },
  { title: "What's the difference between the app and website?", description: "Comparison of mobile app vs website experience.", section: "miscellaneous", content: "App offers faster checkout, push notifications for deals, and exclusive app-only discounts. Website has full functionality.", display_order: 12 },
  { title: "What is dynamic pricing and how does it work?", description: "Explanation of price changes and deals.", section: "miscellaneous", content: "Prices change based on demand, inventory, and seasonal sales. Set price alerts to get notified of price drops.", display_order: 13 },
  { title: "How do I set up price alerts for products?", description: "Guide to getting notifications for price changes.", section: "miscellaneous", content: "Click bell icon on product page to set alert. Get notified when price drops or item is back in stock.", display_order: 14 },
  { title: "What does 'out of stock' mean and when will it be back?", description: "Information about product availability status.", section: "miscellaneous", content: "Product is not currently available. Enable 'Notify Me' for restock alerts. Stock updates vary by product.", display_order: 15 },
  { title: "Can I pre-order out of stock items?", description: "Information about pre-ordering unavailable products.", section: "miscellaneous", content: "Pre-order available for some items. You'll pay now and receive item first once stock arrives.", display_order: 16 },
  { title: "How do I check if a product size will fit me?", description: "Guide to using size charts and fit information.", section: "miscellaneous", content: "Check Size Guide on product page. Compare your measurements. Many products show fit reviews from buyers.", display_order: 17 },
  { title: "How do I find similar or recommended products?", description: "Guide to discovering related items.", section: "miscellaneous", content: "See 'You might also like' and 'Customers bought together' sections. Personalized recommendations in My Account.", display_order: 18 },
  { title: "How do I manage multiple wishlists?", description: "Steps to organize products into different wishlists.", section: "miscellaneous", content: "Create multiple wishlists from Wishlist page. Name them (gifts, personal, home, etc.) for easy organization.", display_order: 19 },
  { title: "Can I share my wishlist with friends and family?", description: "Options for sharing your wishlist with others.", section: "miscellaneous", content: "Go to Wishlist > Share > Copy link or send via email. Friends can view and even buy items as gifts.", display_order: 20 },
  { title: "What should I do if I find a bug or technical issue?", description: "Steps to report website or app problems.", section: "miscellaneous", content: "Go to My Account > Support > Report Bug. Provide details and screenshots. Our tech team will investigate within 24 hours.", display_order: 21 },
  { title: "How do I provide feedback or suggestions?", description: "How to share your ideas for improving Himanshu.", section: "miscellaneous", content: "Visit My Account > Support > Feedback. Share suggestions for features or improvements. We love hearing from customers.", display_order: 22 },
  { title: "What are the system requirements to use Himanshu website?", description: "Technical requirements for smooth browsing experience.", section: "miscellaneous", content: "Works on all modern browsers (Chrome, Safari, Firefox, Edge). Minimum 2GB RAM recommended. Mobile browser compatible.", display_order: 23 },
  { title: "Why is the website running slowly for me?", description: "Troubleshooting steps for slow website performance.", section: "miscellaneous", content: "Clear browser cache, disable extensions, check internet speed, try incognito mode. Contact support if issue persists.", display_order: 24 },
  { title: "Does Himanshu have any seasonal sales or special events?", description: "Information about sales, festivals, and special events.", section: "miscellaneous", content: "Yes! Festival sales, Birthday Month specials, Flash sales, and Clearance events. Subscribe to get early notifications.", display_order: 25 },
  { title: "How can I get notified about upcoming sales and deals?", description: "Ways to stay updated on special offers.", section: "miscellaneous", content: "Enable notifications in app, subscribe to newsletter, follow social media, or add calendar reminders.", display_order: 26 },
  { title: "How can I contact Himanshu customer support?", description: "Complete list of support channels and response times.", section: "miscellaneous", content: "Email: support@Himanshu.com | WhatsApp: +91-XXXXX | Chat: Available 9AM-9PM IST daily. Average response: 2 hours.", display_order: 27 },
  { title: "What are Himanshu's business hours?", description: "Operating hours and availability information.", section: "miscellaneous", content: "We operate 24/7. Customer support: 9AM-9PM IST, Monday-Sunday. Orders processed throughout the day.", display_order: 28 },
  { title: "How can I unsubscribe from marketing emails?", description: "Steps to opt out of promotional communications.", section: "miscellaneous", content: "Click 'Unsubscribe' link at bottom of any email. Or go to My Account > Email Preferences > Disable Promotions.", display_order: 29 },
  { title: "What search features does Himanshu have?", description: "Advanced search capabilities and tips.", section: "miscellaneous", content: "Use filters, sorting, saved searches, and price range selection. Our search learns your preferences over time.", display_order: 30 },
  { title: "How do recommendations work on Himanshu?", description: "Understanding personalized recommendations.", section: "miscellaneous", content: "Based on your browsing, purchases, and wishlist. Machine learning refines suggestions the more you shop.", display_order: 31 },
  { title: "Can I compare products on Himanshu?", description: "Information about comparing multiple items.", section: "miscellaneous", content: "Add items to comparison tool. View side-by-side specs, prices, ratings, and reviews of up to 5 products.", display_order: 32 },
  { title: "What browser should I use for best experience?", description: "Recommended browsers for optimal performance.", section: "miscellaneous", content: "Chrome or Firefox recommended for latest features. Safari and Edge also fully supported. Avoid very old browser versions.", display_order: 33 },
]

export default async function run() {
  console.log(`🌱 Preparing to create ${FAQ_ARTICLES.length} FAQ articles manually...`)

  for (const [index, article] of FAQ_ARTICLES.entries()) {
    console.log(`[${index + 1}/${FAQ_ARTICLES.length}] ${article.section}: ${article.title}`)
  }

  console.log(`\n✅ Ready to paste into database. Total articles: ${FAQ_ARTICLES.length}`)
  console.log(`
Distribution:
- Buying & Orders: 17
- Shipping: 13
- Payments: 20
- Account: 20
- Trust & Safety: 12
- Miscellaneous: 33
  `)
}
